pipeline {
    agent any

    environment {
        TELEGRAM_TOKEN = credentials('TELEGRAM_TOKEN')
        TELEGRAM_CHAT_ID = '1221106616'
    }

    stages {

        stage('Clonar codigo') {
            steps {
                echo 'Clonando el repositorio...'
                checkout scm
            }
        }

        stage('Escanear vulnerabilidades') {
            steps {
                echo 'Escaneando con Trivy...'
                sh '''
                    trivy fs app \
                    --exit-code 1 \
                    --severity HIGH,CRITICAL \
                    --format table \
                    > reporte-trivy.txt 2>&1 || true
                '''
            }
        }

        stage('Escanear codigo fuente') {
            steps {
                echo 'Escaneando con Semgrep...'
                sh '''
                    semgrep scan app \
                    --config=p/owasp-top-ten \
                    --config=p/secrets \
                    --text \
                    > reporte-semgrep.txt 2>&1 || true
                '''
            }
        }

        stage('Evaluar reportes') {
            steps {
                script {
                    def reporteTrivy = readFile('reporte-trivy.txt')
                    def reporteSemgrep = readFile('reporte-semgrep.txt')

                    echo '=== REPORTE TRIVY ==='
                    echo reporteTrivy

                    echo '=== REPORTE SEMGREP ==='
                    echo reporteSemgrep

                    if (reporteTrivy.contains('HIGH') || reporteTrivy.contains('CRITICAL')) {
                        error('Trivy: Dependencias vulnerables encontradas. Despliegue bloqueado.')
                    }

                    if (reporteSemgrep.contains('ERROR')) {
                        error('Semgrep: Vulnerabilidades en codigo fuente encontradas. Despliegue bloqueado.')
                    }

                    echo 'Codigo limpio. Continuando...'
                }
            }
        }

        stage('Desplegar app') {
            steps {
                echo 'Desplegando la app...'
                sh 'docker-compose up -d --build'
            }
        }

    }

    post {
        failure {
            sh """
                curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
                -d chat_id=${TELEGRAM_CHAT_ID} \
                -d text='Despliegue BLOQUEADO por vulnerabilidades en el codigo'
            """
        }
        success {
            sh """
                curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
                -d chat_id=${TELEGRAM_CHAT_ID} \
                -d text='App desplegada exitosamente. Sin vulnerabilidades detectadas'
            """
        }
    }
}
